# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vk0EegJx2zajqPPukfV3QS7Rl_grZrIb

# Twitter Stock Market Analysis using Python

* Twitter started its journey in the stock market in 2013. So to analyze the complete timeline of Twitter in the stock market, we need the stock price data of Twitter from 2013 to 2023.

* Now let’s start with the task of Twitter Stock Market Analysis by importing the necessary Python libraries and the dataset.
"""

import pandas as pd
import datetime
from datetime import date, timedelta
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly_white"

data = pd.read_csv("TWTR.csv")
print(data.head())

print(data.info())

"""* The Date column is an object in this dataset. We will convert it into a datetime data type later.
* Now, let’s have a look at whether this dataset contains any null values or not :
"""

print(data.isnull().sum())

"""* There are five null values in each column except the date column.
* Let’s remove the rows with null values and move further:
"""

data = data.dropna()

data.describe().transpose()

"""* Now let’s have a look at the stock prices of Twitter over the years:"""

figure = go.Figure(data=[go.Candlestick(x=data["Date"],
                                        open=data["Open"],
                                        high=data["High"],
                                        low=data["Low"],
                                        close=data["Close"])])
figure.update_layout(title = "Twitter Stock Prices Over the Years",
                     xaxis_rangeslider_visible=False)
figure.show()

"""* So since the introduction of Twitter in the stock market, it was only profitable at the beginning and 2021. Let’s visualize a bar chart to analyze the stock prices of Twitter in detail:"""

figure = px.bar(data,
                x = "Date",
                y= "Close",
                color="Close")
figure.update_xaxes(rangeslider_visible=True)
figure.show()

"""* The above graph shows the stock prices of Twitter over the years. You can use the range slider below to zoom into a particular time period. Look at the image as an example.

*Using the range slider, we can see that the first quarter of 2021 was the best time period for Twitter over the years in the stock market.
* We can also assign buttons to control time periods.
* Let’s add buttons to analyze the stock prices of Twitter in different time periods:
"""

figure = px.bar(data, x = "Date", y= "Close", color="Close")
figure.update_xaxes(rangeslider_visible=True)
figure.update_layout(title = "Twitter Stock Prices Over the Years",
                     xaxis_rangeslider_visible=False)
figure.update_xaxes(
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=3, label="3m", step="month", stepmode="backward"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(count=2, label="2y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)
figure.show()

"""* The buttons in the visualization above will help you understand the stock prices of Twitter at different time periods.

* Now let’s have a look at the complete timeline of Twitter in the stock market:
"""

data["Date"] = pd.to_datetime(data["Date"],
                              format = '%Y-%m-%d')
data['Year'] = data['Date'].dt.year
data["Month"] = data["Date"].dt.month
fig = px.line(data,
              x="Month",
              y="Close",
              color='Year',
              title="Complete Timeline of Twitter")
fig.show()

import matplotlib.pyplot as plt
import seaborn as sns

numerical_columns = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
correlation_matrix = data[numerical_columns].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', square=True)
plt.title('Correlation Heatmap of Twitter Stock Market Data')
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='High', y='Low', data=data)
plt.title('Twitter Stock High vs Low Prices')
plt.xlabel('High Price')
plt.ylabel('Low Price')
plt.show()

fig, ax = plt.subplots()
ax.set_yscale('log')
ax.hist([data['Open'], data['High'], data['Low'], data['Close']], bins=20, stacked=True, label=['Open', 'High', 'Low', 'Close'])
ax.set_xlabel('Price')
ax.set_ylabel('Frequency')
ax.set_title('Stacked Histogram of Twitter Stock Prices')
ax.legend()
plt.show()

sns.set(style="ticks")
g = sns.JointGrid(data=data, x='Date', y='Close', height=6, ratio=5)
g.plot_joint(sns.scatterplot, color='b')
g.plot_marginals(sns.histplot, kde=True, color='b')
plt.xticks(rotation=45, ha='right')
plt.title('Twitter Stock Close Price Scatterplot with Marginal Ticks')
plt.xlabel('Date')
plt.ylabel('Closing Price')
plt.show()

"""*******************************************************
So since the introduction of Twitter in the stock market, 2014 went well for Twitter in the first four years. 2016 and 2017 were the worst for Twitter in the stock market. Its stock prices went up in 2018, 2019, and 2020. And then came 2021, the best year for Twitter in the stock market. Twitter reached its highest-ever stock price in the year 2021. But the stock prices of Twitter went down again in 2022.
"""